
apiVersion: apps/v1
kind: Deployment
metadata:
    name: globomantics
  labels:
        app: globomantics
spec:
    replicas: 2
  selector:
        matchLabels:
                app: globomantics
  template:
        metadata:
                labels:
                          app: globomantics
    spec:
            containers:
                      - name: globomantics
          image: nginx:1.27
          ports:
                        - containerPort: 80
          resources:
                        requests:
                                        cpu: 100m
              memory: 128Mi
            limits:
                            cpu: 250m
              memory: 256Mi
          livenessProbe:
                        httpGet:
                                        path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
                        httpGet:
                                        path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
inerPort: 80
